spring:
  config:
    import: classpath:config.yml
  application:
    name: arc-raiders
#  main:
#    allow-bean-definition-overriding: true
#    web-application-type: reactive
  datasource:
    url: "jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

server:
  port: 8081
  reactive:
    session:
      timeout: 30m
  netty:
    connection-timeout: 30s